### ISSUE TITLE
Website incorrectly points to sdk.gnome.org

### ISSUE THREAD

**Issue by bochecha** [xhorak/firefox-devedition-flatpak#103]
The stable GNOME runtimes used to be provided at https://sdk.gnome.org/.

This hasn't been updated for a while, and is now a stale repo: only the master GNOME runtimes are still distributed there.

Stable GNOME runtimes are now built and distributed on Flathub.

The website at https://firefox-flatpak.mojefedora.cz/ says:

> The Gnome Runtime is required to run the application. To install its repository execute following command:
> 
>     flatpak remote-add --from gnome https://sdk.gnome.org/gnome.flatpakrepo

Please change the instructions to point to Flathub, otherwise people might be installing some very old runtimes.

**Comment by xhorak** [comment]
Thanks for the report, it should be fine on the page now.
