### ISSUE TITLE
Text overlap in Nightly Wayland

### ISSUE THREAD

**Issue by mogenson** [xhorak/firefox-devedition-flatpak#106]
Some characters overlap in the Firefox UI. Websites render correctly.

![screenshot from 2018-11-05 22-02-02](https://user-images.githubusercontent.com/900731/48041089-a44a6000-e149-11e8-811b-b578e5344c56.png)

Setting the Font and font size have no effect. There are also no Advanced options under Font.

![screenshot from 2018-11-05 22-03-27](https://user-images.githubusercontent.com/900731/48041162-fc816200-e149-11e8-866e-2a3d8d903cdf.png)

**Comment by stransky** [comment]
Yes, I also see that on Fedora 29 / flatpak. Does not appears on plain nightly.

**Comment by martin-jamszolik** [comment]
I Concur as well, 
Fedora 29 using flatpak

**Comment by xhorak** [comment]
This seems to be related to the gnome runtime. I was able to fix it by removing gnome runtime from gnome flatpak prepository and switch to gnome runtime from flathub. The gnome repository seems not to be updated for long time: https://blogs.gnome.org/alexl/2017/11/13/gnome-apps-migrated-to-flathub/

I use following commands to remove gnome repository:
```
flatpak uninstall org.mozilla.FirefoxNightly
flatpak uninstall --unused
flatpak remote-delete gnome
```
and having flathub repository installed:
```
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
```
install again as described in: https://firefox-flatpak.mojefedora.cz/

**Comment by mogenson** [comment]
Thanks! I had accepted the default option of adding the sdk.gnome.org repo.

**Comment by rugk** [comment]
Dupe of https://github.com/xhorak/firefox-devedition-flatpak/issues/126#issuecomment-495101543
