### ISSUE TITLE
FirefoxNightly fails to start (Arch, Sway)

### ISSUE THREAD

**Issue by edrex** [xhorak/firefox-devedition-flatpak#107]
When I first installed the flatpak build a few days ago, I was seeing a crash at startup like this:

```
❯ flatpak run org.mozilla.FirefoxNightly --no-remote                       
Gdk-Message: Error reading events from display: Invalid argument
[Child 65, Chrome_ChildThread] WARNING: pipe error (52): Connection reset by peer: file /run/build/firefox/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 363
[Child 65, Chrome_ChildThread] WARNING: pipe error (3): Connection reset by peer: file /run/build/firefox/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 363
 ```

After updating the flatpak build just now, firefox seems to fall back to XWayland. Forcing wayland by setting `GDK_BACKEND=wayland` still results in the crash though.

I'm not sure if this is an incompatibility of FF with Sway, of the build with Arch, or an upstream bug that everyone is hitting.

**Comment by stransky** [comment]
Sway is not supported yet, I'm going to look at it.

**Comment by edrex** [comment]
Is it the build that has the issue or upstream?

Thanks @stransky. These builds are a real service to the desktop Linux ecosystem. :medal_military:

**Comment by uwqwxing886** [comment]
Does firefox launch if you clear the clipboard before running it? See https://github.com/swaywm/sway/issues/3170.

**Comment by edrex** [comment]
@uwqwxing886 thanks for the reference. while I didn't find a command to clear the clipboard, after updating to a sway build using the latest wlroots head with https://github.com/swaywm/wlroots/pull/1380, the FF build launches.
