### ISSUE TITLE
Firefox nightly runs in xwayland mode

### ISSUE THREAD

**Issue by nushoin** [xhorak/firefox-devedition-flatpak#108]
Nightly version 20181108022619 runs in xwayland mode instead of Wayland.
I think it's related to [https://bugzilla.mozilla.org/show_bug.cgi?id=1503592](https://bugzilla.mozilla.org/show_bug.cgi?id=1503592) (Make X11 Gtk backend default).

Probably related to #107 as well. If I force the wayland backend by running from the terminal `GDK_BACKEND=wayland flatpak run org.mozilla.FirefoxNightly` it does use a Wayland session.

**Comment by stransky** [comment]
Yes, thant's correct. Mozilla is going to produce Wayland enabled builds and the X11 backend has to be the default one. Jan is going to fix that on flatpak side.

**Comment by xhorak** [comment]
Fixed by 0debfa24965eceb966fc9f181417ce32dedb8fdd.
