### ISSUE TITLE
FirefoxNightly Won't Start on an Xorg Session Anymore

### ISSUE THREAD

**Issue by Saroufim** [xhorak/firefox-devedition-flatpak#109]
After today's update, FirefoxNightly won't start on Xorg at all but it would run perfectly fine on Wayland.

**Comment by ajzone** [comment]
I'm in the same situation.  When attempting to run Firefox Nightly I get the following:

$ flatpak run org.mozilla.FirefoxNightly 
1541939927362	addons.xpi	WARN	Error loading bootstrap.js for screenshots@mozilla.org: Error opening input stream (invalid filename?): jar:file:///app/lib/firefox/browser/features/screenshots@mozilla.org.xpi!/bootstrap.js
1541939927363	addons.xpi	WARN	Add-on screenshots@mozilla.org is missing bootstrap method startup
1541939927364	addons.xpi	WARN	Error loading bootstrap.js for webcompat-reporter@mozilla.org: Error opening input stream (invalid filename?): jar:file:///app/lib/firefox/browser/features/webcompat-reporter@mozilla.org.xpi!/bootstrap.js
1541939927364	addons.xpi	WARN	Add-on webcompat-reporter@mozilla.org is missing bootstrap method startup
1541939927365	addons.xpi	WARN	Error loading bootstrap.js for webcompat@mozilla.org: Error opening input stream (invalid filename?): jar:file:///app/lib/firefox/browser/features/webcompat@mozilla.org.xpi!/bootstrap.js
1541939927366	addons.xpi	WARN	Add-on webcompat@mozilla.org is missing bootstrap method startup

(firefox:3): Gtk-WARNING **: cannot open display: :99.0

Here's the flatpak info if it matters, I am running this in the user context.  IDK if running it as system would work, I'll try that.

$ flatpak info org.mozilla.FirefoxNightly 
Ref: app/org.mozilla.FirefoxNightly/x86_64/master
ID: org.mozilla.FirefoxNightly
Arch: x86_64
Branch: master
Origin: org.mozilla.FirefoxRepo
Collection ID: 
Date: 2018-11-09 09:28:36 +0000
Subject: Build of org.mozilla.FirefoxNightly
Commit: 555f4686bab087437157e623621679f7bd499317228071b779d9431ca2361aee
Parent: e003226a819496e71436000bbf2acf7b3e086c849a5a20777de6cac0840d4e40
Location: /home/remote/azone/.local/share/flatpak/app/org.mozilla.FirefoxNightly/x86_64/master/555f4686bab087437157e623621679f7bd499317228071b779d9431ca2361aee
Installed size: 272.0 MB
Runtime: org.gnome.Platform/x86_64/3.26
Sdk: org.gnome.Sdk/x86_64/3.26

org.mozilla.FirefoxNightly/x86_64/master               user,current

**Comment by ajzone** [comment]
Looking like rolling back to commit e003226a819496e71436000bbf2acf7b3e086c849a5a20777de6cac0840d4e40, the one from the 8th, resolves the issue.

So the issue was introduced in commit 555f4686bab087437157e623621679f7bd499317228071b779d9431ca2361aee on 2018-11-09

**Comment by JBBgameich** [comment]
It seems like https://github.com/xhorak/firefox-devedition-flatpak/commit/ce9f2df03b04f962bcc34fa8dbf7bced9df97a74 introduced the problem.

**Comment by xhorak** [comment]
This should be fixed now by part of 2b32a079c0ed625a15d4a0a34ebe1e9e977c446d changeset, sorry for the problems.
