### ISSUE TITLE
FirefoxNightly is not updated daily

### ISSUE THREAD

**Issue by lionirdeadman** [xhorak/firefox-devedition-flatpak#110]
Simple as the title implies, the flatpak is not updated every day like it should be from my understanding.

**Comment by narwhalofages** [comment]
@lionirdeadman, is the version you are running showing up as "65.0a1 (2018-11-16) (64-bit)"? That would imply that this package hasn't been updated in two weeks.

I don't know if the Fedora/Red Hat team have committed specifically to updating this flatpak every day, but it also feels like it would kind of be implied in offering it in the first place. Hopefully someone can step in and clarify for us.

**Comment by lionirdeadman** [comment]
Yup, I have the same version.

**Comment by xhorak** [comment]
This should be resolved now.
