### ISSUE TITLE
New builds

### ISSUE THREAD

**Issue by treba123** [xhorak/firefox-devedition-flatpak#115]
The last build seems to be from from January 19. Can you have a look to have it build again? Thanks for this cool stuff! :)

**Comment by develop7** [comment]
@xhorak pretty please?

**Comment by stransky** [comment]
@xhorak is on sick leave and may be available in ~month.

**Comment by treba123** [comment]
Github misses a sad reaction :(
Get well soon, @xhorak !

**Comment by jgarciao** [comment]
@xhorak I hope you are getting better. Thanks for your work!

**Comment by develop7** [comment]
@xhorak get better soon!

**Comment by rugk** [comment]
Any news here? Possibly this is also related to https://github.com/xhorak/firefox-devedition-flatpak/issues/121

**Comment by xhorak** [comment]
This should be fixed today finally.

**Comment by kaymio** [comment]
Great to see you back in action! Hope you are well :smiley:
