### ISSUE TITLE
[Bug?] Native notifications

### ISSUE THREAD

**Issue by lionirdeadman** [xhorak/firefox-devedition-flatpak#117]
The flatpak doesn't use native notifications and instead uses Firefox's built-in notification system.

**Comment by kirbyfan64** [comment]
The manifest needs to add `--talk-name=org.freedesktop.Notifications` for this to work.

**Comment by ndarilek** [comment]
I submitted a PR implementing the fix that should close this, but it hasn't been merged yet. Is there anything wrong with it? I unfortunately can't test it here--too little disk space for flatpak builds at the moment--but it would be useful to merge if it works. I'm a screen reader user, and Firefox's native notifications are inaccessible while its desktop notifications are fine. I know I can override this flatpak and grant access, but I'm trying to improve things for everyone and not just myself.

Thanks.
