### ISSUE TITLE
context menu lbm

### ISSUE THREAD

**Issue by id4343** [xhorak/firefox-devedition-flatpak#122]
if i push context menu on page i don't can push left button moue, this menu invisibility, but if i push right button and no drop right button push left button i can do cut, copy, paste. also can use ctl+lbm for it, but it do if u want use bookmarks new tab.

u can do correctly work it? thanks.

**Comment by erAck** [comment]
If I understood correctly this was about context menu not staying on screen to be able to click an item thereafter, which nicely works (now). Otherwise I didn't understand anything.
