### ISSUE TITLE
Marionette, not defined entity?

### ISSUE THREAD

**Issue by kaymio** [xhorak/firefox-devedition-flatpak#123]
Since the last update on my main system I get this when starting the DevEdition:

`LANG=C flatpak run org.mozilla.FirefoxDevEdition
JavaScript error: resource://gre/modules/AddonManager.jsm, line 850: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIStringBundle.GetStringFromName]
1555573093495   Marionette      FATAL   XML-Verarbeitungsfehler: Nicht definierte Entität
Adresse: chrome://browser/content/browser.xul
Zeile Nr. 962, Spalte 7:      <menuitem id="context-savelinktopocket"
------^
JavaScript error: resource://gre/modules/AutoCompletePopup.jsm, line 112: NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIObserverService.removeObserver]`

Unfortunately the system I'm on has the German locale set and the LANG=C doesn't change the output.
To remedy that I tried

`flatpak update --subpath=/en org.mozilla.FirefoxDevEdition`

which now results in:

`flatpak run org.mozilla.FirefoxDevEdition
bwrap: execvp firefox: No such file or directory`

and verbose:

`flatpak -v run org.mozilla.FirefoxDevEdition

F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/nackt/.local/share/flatpak
F: Opening user flatpak installation at path /home/nackt/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/nackt/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 2180479318
F: Allocated instance id 1176432418
F: Add defaults in dir /org/mozilla/FirefoxDevEdition/
F: Add locks in dir /org/mozilla/FirefoxDevEdition/
F: Allowing dri access
F: Allowing homedir access
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/nackt/.config/pulse/client.conf': Fehler beim Öffnen der Datei »/home/nackt/.config/pulse/client.conf«: Datei oder Verzeichnis nicht gefunden
F: Allowing session-dbus access
F: Running 'bwrap --args 36 xdg-dbus-proxy --args=38'
F: Running 'bwrap --args 36 firefox'
bwrap: execvp firefox: No such file or directory
`
Flatpak 1.3.2, or more precisely 1.3.2+6+g00dfce52-1
My specs can be found here https://8n1.org/14989/da47

**Comment by kaymio** [comment]
I was able to revert the self inflicted subpath problem with 

flatpak update --subpath= org.mozilla.FirefoxDevEdition

Now the verbose output looks like this again:

`flatpak -v run org.mozilla.FirefoxDevEdition
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/nackt/.local/share/flatpak
F: Opening user flatpak installation at path /home/nackt/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/nackt/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 918717151
F: Allocated instance id 2878867237
F: Add defaults in dir /org/mozilla/FirefoxDevEdition/
F: Add locks in dir /org/mozilla/FirefoxDevEdition/
F: Allowing dri access
F: Allowing homedir access
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/nackt/.config/pulse/client.conf': Fehler beim Öffnen der Datei »/home/nackt/.config/pulse/client.conf«: Datei oder Verzeichnis nicht gefunden
F: Allowing session-dbus access
F: Running 'bwrap --args 36 xdg-dbus-proxy --args=38'
F: Running 'bwrap --args 36 firefox'
JavaScript error: resource://gre/modules/AddonManager.jsm, line 850: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIStringBundle.GetStringFromName]
1555660211470   Marionette      FATAL   XML-Verarbeitungsfehler: Nicht definierte Entität
Adresse: chrome://browser/content/browser.xul
Zeile Nr. 962, Spalte 7:      <menuitem id="context-savelinktopocket"
------^
JavaScript error: resource://gre/modules/AutoCompletePopup.jsm, line 112: NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIObserverService.removeObserver]`

With my limited knowledge I think I can deduct that there is a problem with the AddonManager. I'm not sure why a chrome extension would be related to my Firefox install. I'm at a loss here.

**Comment by kaymio** [comment]
After the most recent update the output has changed:

https://8n1.org/15008/465b

**Comment by kaymio** [comment]
Another update: https://8n1.org/15093/247a

Still can't run the DevEdition. Should I un- and reinstall? Will I lose my profile?

**Comment by Blaimi** [comment]
I'm having the same – or at least a very similar.

System: Debian 10 testing with all updates.

I tried uninstalling all flatpak-packages and reinstalling org.mozilla.FirefoxDevEdition and renaming ~/.var/app/org.mozilla.FirefoxDevEdition with no success.

The Problem started for me around Monday (20.05.2019).

Firefox Nightly is running on the same system without errors (fresh installation).

https://8n1.org/15230/ad07

**Comment by Blaimi** [comment]
starting with the `-safe-mode`-parameter fixed the issue for a moment. after that, it complained that my profile was touched by a newer version of firefox so I had to create a new profile. It's working again now, but I don't know what the problem was.

I also don't know why it refused to start because of the newer version thing but I think this is unrelated.

**Comment by erAck** [comment]
I guess this is outdated now.
