### ISSUE TITLE
Fuzzy text in HiDPI mode

### ISSUE THREAD

**Issue by rugk** [xhorak/firefox-devedition-flatpak#126]
In the flatpak the text looks _a little_ broken… :wink: 

![grafik](https://user-images.githubusercontent.com/11966684/57836794-c7715e80-77c1-11e9-82ab-7cdeaf3b430d.png)

**Note:** This _only_ affects the Firefox UI. Websites are displayed just fine.

**Comment by stransky** [comment]
Yes, I see that on non-flatpak version too. Maybe we don't react well on theme change or so. I usually see that after restore from suspend or after screen unlock.

**Comment by rugk** [comment]
It got worse… I have some really great characters here then:
![grafik](https://user-images.githubusercontent.com/11966684/58159486-e9188d00-7c7c-11e9-804f-0dd3975963ff.png)

---

I have a stable Firefox version from Fedora, where this did not happen. I can _always_ reproduce it with Firefox Dev Edition, however. Since some time already, it worked in the past.
(I see no correlation with theme changes or screen unlocks.)

Firefox Nightly in flatpak works fine. :thinking:

**Comment by Empornium** [comment]
I've had both versions of this, the first was workable, but now...

![Screenshot from 2019-05-20 15-06-54](https://user-images.githubusercontent.com/25505583/58217373-6fbf7f80-7cfa-11e9-961c-3c4d6e29b48c.png)

**Comment by xhorak** [comment]
Please be sure you have the `org.gnome.Platform` and `org.freedesktop.Platform` installed from flathub and *not* from sdk.gnome.org. Use `flatpak list` and look for Origin column to check it.

**Comment by rugk** [comment]
Uhm… it's a little complicated…

```sh
$ flatpak list | grep gnome
default	org.freedesktop.Platform.GL.default		1.6	x86_64	gnome	system
GNOME Application Platform version 3.24 - Shared libraries used by GNOME applications	org.gnome.Platform		3.24	x86_64	gnome	system
GNOME Application Platform version 3.26 - Shared libraries used by GNOME applications	org.gnome.Platform		3.26	x86_64	flathub	system
GNOME Application Platform version 3.28 - Shared libraries used by GNOME applications	org.gnome.Platform		3.28	x86_64	flathub	system
GNOME Application Platform version 3.30 - Shared libraries used by GNOME applications	org.gnome.Platform		3.30	x86_64	flathub	system
$ flatpak list | grep "freedesktop.Platform     "
Freedesktop.org Application Platform version 1.6 - Shared libraries provided by freedesktop.org	org.freedesktop.Platform	1.6	1.6	x86_64	flathub	system
Freedesktop Platform - Shared libraries	org.freedesktop.Platform	18.08.30	18.08	x86_64	flathub	system
```

So freedesktop is okay, `org.gnome.Platform` is not, as it seems.

**Comment by xhorak** [comment]
Yes, remove `org.gnome.Platform//3.24` and reinstall it from flathub. The gnome repository is not updated for long time.

**Comment by rugk** [comment]
Thanks, works now. :smile:
