### ISSUE TITLE
Update please

### ISSUE THREAD

**Issue by rugk** [xhorak/firefox-devedition-flatpak#131]
https://github.com/xhorak/firefox-devedition-flatpak/issues/81 again.

Firefox 68 is already stable now, but you still ship the beta version of v68 in the Firefox dev edition.

Also, maybe consider somehow to automate the update process?

**Comment by lionirdeadman** [comment]
Nightly updates have also seemingly stopped, I believe the build server is failing to build it.

**Comment by rugk** [comment]
Any news, @xhorak? It's really not great having to use outdated software… :thinking:

**Comment by xhorak** [comment]
We've got some problems on building machines, the new version should be available ATM.

**Comment by rugk** [comment]
Thanks, I can conform it's updated.
