### ISSUE TITLE
mark repository as deprecated

### ISSUE THREAD

**Issue by okias** [xhorak/firefox-devedition-flatpak#133]
since I followed Debian page to get flatpak Firefox Nightly running here and it seems rely on old GNOME 3.28 runtime and no progress has been done, I propose marking this repo as deprecated.

Thank you

**Comment by thebitstick** [comment]
Uhm, I'd say marking it as _deprecated_ is a bit much.
How about submitting a PR to upgrade it to 3.32 or 3.34?
A bit more constructive..

**Comment by okias** [comment]
Well of course that is option :) i just needed quicklu install nighly on one Debian machine. In the end I just unpacked tar and run&test it .

**Comment by thebitstick** [comment]
There's still people who use this repo.
There are still some fixes that haven't made their way into stable Firefox...
...IS WHAT I WOULD SAY if the current stable WASN'T version 70.
I'm probably going to have to move over to the Fedora Flatpak for Firefox which is stable version 70, and right now this outdated Nightly is ALSO version 70.
But all it takes is @xhorak to ensure the build server (which I'm assuming exists) is functioning properly.

**Comment by tpopela** [comment]
We will be updating the GNOME runtime, once we fix the current crash that makes this Flatpak unusable.

**Comment by okias** [comment]
@tpopela thank you for looking into it.

**Comment by erAck** [comment]
Meanwhile updated to 3.34 runtime.
