### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by fishxz** [xhorak/firefox-devedition-flatpak#134]
Hey, since the update from yesterday FF (both nightly and dev) crashes with on start:
```/app/bin/firefox: line 8:     3 Segmentation fault      (core dumped) firefox-bin $*```

**Comment by thebitstick** [comment]
This repo is so broken and far behind on updates that the stable OCI Fedora Flatpak repository has a more update to date version of Firefox available.
I'd recommend switching over. Cause this repo is practically dead.

**Comment by robinvd** [comment]
@thebitstick can you link to that repo? I can't seem to find the package

**Comment by FastOSlinux** [comment]
> This repo is so broken and far behind on updates that the stable OCI Fedora Flatpak repository has a more update to date version of Firefox available.
> I'd recommend switching over. Cause this repo is practically dead.

but firefox fedora doesn't work with all codecs like this, does it?

**Comment by fishxz** [comment]
yes, h264 doesnt work there and thats what i need.

**Comment by thebitstick** [comment]
https://docs.fedoraproject.org/en-US/flatpak/concepts/#_oci_images

**Comment by sebastien** [comment]
Same problem here on Fedora 30 -- @thebitstick, do you happen to know how to install Firefox Dev as a Flatpak from the OCI images? I didn't find it on [the registry](https://registry.fedoraproject.org/).

**Comment by thebitstick** [comment]
@sebastien You... don't. The Fedora Flatpak OCI doesn't build for Firefox Dev, unfortunately.
However, if you just want a more up-to-date Firefox, this repo is so far behind that the version on the OCI actually newer.

**Comment by sebastien** [comment]
Ah, too bad. I don't really need the bleeding edge, I'm using FF dev for general web development. Let's cross our fingers and hope that segfault goes away on the next build.

**Comment by rugk** [comment]
Can't @xhorak fix this segmentation fault thing? I could provide diagnostic data, if needed…

**Comment by tpopela** [comment]
@xhorak started to look at this issue. Sorry, we were occupied by things with higher priority.

**Comment by ritzk** [comment]
Not able to reproduce this with latest nightly (73a) built locally using  #140 .

**Comment by rugk** [comment]
yeah dev edition works again too
