### ISSUE TITLE
org.mozilla.FirefoxDevEdition won't build

### ISSUE THREAD

**Issue by lionirdeadman** [xhorak/firefox-devedition-flatpak#139]
Wanted to try it since it now uses shared-modules and 3.34 but it won't build. Also wanted to add that patch you showed which adds openh264 video support but I've not been able to build Firefox yet so here I am.

Here's the log :
[firefox-flatpak.log](https://github.com/xhorak/firefox-devedition-flatpak/files/3976354/firefox-flatpak.log)

**Comment by ritzk** [comment]
You might want to try - https://github.com/xhorak/firefox-devedition-flatpak/pull/140

**Comment by erAck** [comment]
Current version builds fine.
