### ISSUE TITLE
Add 'Open Profile Manager'

### ISSUE THREAD

**Issue by jtagcat** [xhorak/firefox-devedition-flatpak#144]
![image](https://user-images.githubusercontent.com/38327267/78037830-93604700-735b-11ea-9d04-04e06473885a.png)
Add `Open Profile Manager` to the right click menu, what makes Firefox run with `--ProfileManager`.
It's quite easy to do, I can do a MR.
Thoughts? Any opposition?

**Comment by erAck** [comment]
Sure, give it a try.
