### ISSUE TITLE
Better documentation on build enviroment

### ISSUE THREAD

**Issue by jtagcat** [xhorak/firefox-devedition-flatpak#145]
Got errors with the following not installed:
 - rust
 - flatpak-builder

I installed them using rustup and dnf.

I still failed to compile with many errors. _Help please, I just wanted to test if my commit closing #144 would work fine._ 
Have never compiled ff and am helpless.
https://sh.c7.ee/u6Icq/i-am-helpless-build.log

**Comment by erAck** [comment]
Well, yes, of course you need flatpak-builder when building flatpaks..
As for Rust, you need Cargo to be installed that depends on Rust. I'll add that to the README.
I don't see "many errors" in the log, in fact only one. The only failure seems to be at the end of the log
```
desktop-file-install --dir /app/share/applications org.mozilla.Firefox.desktop
/app/share/applications/org.mozilla.Firefox.desktop: error: action group "Desktop Action profilemanager" exists, but there is no matching action "profilemanager"
Error on file "org.mozilla.Firefox.desktop": Failed to validate the created desktop file
```
So exactly the part you modified.

**Comment by erAck** [comment]
Actually `org.mozilla.FirefoxNightly/README.md` already lists the requirements.

**Comment by jtagcat** [comment]
Welcome to over 24h awake, should've looked at it again later.
