### ISSUE TITLE
Firefox Nightly Issue in Flatpak

### ISSUE THREAD

**Issue by jfmccordjr** [xhorak/firefox-devedition-flatpak#149]
When I try to enable Firefox Nightly on a flatpak. I get the following error. Error 32 (Broken pipe) dispatching to Wayland display. Is it possible to get this fixed?

**Comment by erAck** [comment]
Which system and what exactly are you doing to "enable Firefox Nightly on a flatpak"?

**Comment by erAck** [comment]
Insufficient data, closing.
