### ISSUE TITLE
Firefox 52 ESR

### ISSUE THREAD

**Issue by robin-a-meade** [xhorak/firefox-devedition-flatpak#15]
Could we have a flatpak build of Firefox 52 ESR?

At my job, we use the NPAPI plugin to run Oracle Forms. NPAPI [was removed](https://support.mozilla.org/t5/Problems-with-add-ons-plugins-or/Why-do-Java-Silverlight-Adobe-Acrobat-and-other-plugins-no/ta-p/31069) in Firefox 52, but is retained in Firefox 52 ESR.

**Comment by jgarciao** [comment]
I find this very useful too. At work we still use some legacy webapps that require Fifefox 52 ESR because of java applets.

**Comment by FelixSchwarz** [comment]
Having Firefox ESR would also help us testing older (but still supported) versions of Firefox with our webapps. Currently we tend to ignore ESR versions which is mostly fine – until it isn't. ;-)

**Comment by mavit** [comment]
I'm not sure if there's any interest in these things, but I've had a play around with [wrapping upstream's ESR binary with Flatpak](https://github.com/mavit/firefox-devedition-flatpak/commit/6776d0fb295473ca0312d49f97192339448f0ca8), and [building an ESR snapshot from git](https://github.com/mavit/firefox-devedition-flatpak/commit/db5e2b1ab44c4a97923c8fd595e3b4bf8e4311bd).

**Comment by xhorak** [comment]
Sorry, we won't address this. This repository was made mainly to test the latest code with experimental features like Wayland support and running in Flatpak sandbox. If you need to use ESR, please follow @mavit suggestion or download [ESR binaries](https://www.mozilla.org/en-US/firefox/organizations/) directly from mozilla.

With upstream binaries you will also get latest updates of ESR branch.
