### ISSUE TITLE
Add a build from tarballs

### ISSUE THREAD

**Issue by elvisangelaccio** [xhorak/firefox-devedition-flatpak#17]
Firefox git repository is huge and cloning it takes forever with slow internet connections. Please consider adding another firefox build from official firefox release tarballs.

**Comment by xhorak** [comment]
There's a request to allow shallow copies of the repository:
https://github.com/flatpak/flatpak/issues/15
That's the way when it is done.
Mozilla does not provide source tarballs for nightlies as long as I know.

**Comment by elvisangelaccio** [comment]
What about building stable release tarballs? (at least as temporary workaround)

**Comment by elvisangelaccio** [comment]
Hmm I get this error if I try to build the 52.0.1 tarball:

```
ERROR:   ***
  * Building directly in the main source directory is not allowed.
  *
  * To build, you must run configure from a separate directory
  * (referred to as an object directory).
  *
  * If you are building with a mozconfig, you will need to change your
  * mozconfig to point to a different object directory.
  ***
```

This is the patch I used:

```diff
diff --git a/org.mozilla.FirefoxDevEdition/org.mozilla.FirefoxDevEdition.json b/org.mozilla.FirefoxDevEdition/org.mozilla.FirefoxDevEdition.json
index 0287b58..9234c2e 100644
--- a/org.mozilla.FirefoxDevEdition/org.mozilla.FirefoxDevEdition.json
+++ b/org.mozilla.FirefoxDevEdition/org.mozilla.FirefoxDevEdition.json
@@ -123,9 +123,9 @@
           "make-install-args": ["prefix=/app"],
           "sources": [
               {
-                  "type": "git",
-                  "url": "https://github.com/mozilla/gecko-dev",
-                  "branch" : "aurora"
+                  "type": "archive",
+                  "url": "https://ftp.mozilla.org/pub/firefox/releases/52.0.1/source/firefox-52.0.1.source.tar.xz",
+                  "sha256" : "2ea8659c787c6a9d2b1fdadbb3171b3a6d3ef3d61fbaaa8e40fa14cfd0b82dd9"
               },
               {
                   "type": "patch",
```

Any idea what I'm doing wrong?

**Comment by xhorak** [comment]
Sorry for really delayed response. Mozconfig is not properly installed. Please check that it's located in the unpacked directory. This is maybe problem that `firefox-52.0.1.source.tar.xz` contains `firefox-52.0.1` directory while cloning from github does not create that directory. You probably need to use something like:
```"dest-filename": "firefox-52.0.1/.mozconfig"```

Currently we don't consider building from tarballs as long as sha256 changes frequently and tarballs are provided less frequently especially for the nightly.
