### ISSUE TITLE
Add opengl/DRI support

### ISSUE THREAD

**Issue by alexlarsson** [xhorak/firefox-devedition-flatpak#18]
You need to add "--device=dri" to the finish-args, so that firefox has access to whatever devices it needs for opengl. This may work on some drivers/setups without this, but it general you must have it for it to work always.

**Comment by alexlarsson** [comment]
You *may* actually want --device=all, which gives you full device access, and may be needed for e.g. webcam access, until we have a portal story figured out there.

**Comment by xhorak** [comment]
Thanks for the hint, added by d383ef36752c3baf57b630c9f2d37423ac2a6b51
