### ISSUE TITLE
FirefoxNightlyWayland Sync

### ISSUE THREAD

**Issue by MrReSc** [xhorak/firefox-devedition-flatpak#19]
My System:
XPS13, Fedora 25, Kernel 4.9.14-200.fc25.x86_64

As soons as i try to sign on at firefox sync, FirefoxNightlyWayland crashes. I receive the confirmation email from firefox.

**Comment by glaubersm** [comment]
Sync is working on my Arch running NightlyWayland build.

**Comment by stransky** [comment]
Please try non-flatpak build (for instance https://copr.fedorainfracloud.org/coprs/stransky/firefox-wayland/). If you use .deb based distro we'll try to come with debugging steps for flatpak.

**Comment by erAck** [comment]
I guess this is outdated now..
