### ISSUE TITLE
[FirefoxNightly] Save downloads at an user-accessible location

### ISSUE THREAD

**Issue by paulusasol** [xhorak/firefox-devedition-flatpak#24]
## Error description
I just tried downloading some files using the Nightly flatpak, however, I couldn't find them anywhere outside of the flatpak, they apparently landed inside some directory not easily accessible outside the flatpak. It is a little bit annoying being forced to redo a 3.5GiB download.

## Proposed quick-fix
The easiest thing should be to add r/w filesystem access to the users downloads folder using `--filesystem=xdg-download:rw` so that the flatpak has access to the user's download folder.

**Comment by garrett** [comment]
Current workaround: Until a fix lands, you can run the following:

```bash
sudo flatpak override org.mozilla.FirefoxNightly --filesystem=xdg-download
```

...and then restart Firefox. After that, go to preferences and select your download location (and choose your normal downloads folder).

**Comment by glaubersm** [comment]
this workaround does not work with Wayland build.

**Comment by xhorak** [comment]
The `-filesystem=xdg-download:rw` added to the builds. Thanks.
