### ISSUE TITLE
[FirefoxNightly] Enable opening the downloads location out of firefox

### ISSUE THREAD

**Issue by paulusasol** [xhorak/firefox-devedition-flatpak#25]
## Bug description
Even when using the proposed quick-fix to #24 it is impossible to use the open-folder button in firefox downloads page. When pressing the folder button, nothing happens.

## Expected behaviour
A nautilus (or of whatever file-manager one uses) window pops up, showing the folder containing the downloaded file.

**Comment by xhorak** [comment]
This change should fix this, we need to wait to be backported to the stable glib2:
https://git.gnome.org/browse/glib/commit/?id=4c8ab22b95de887af7e233095816c3ae9dd8c10e

**Comment by jurf** [comment]
It still doesn’t work, when can we expect it?

**Comment by erAck** [comment]
So this should actually be closed now. Meanwhile using Gnome 3.34.
