### ISSUE TITLE
[FirefoxNightlyWayland] Can't use keybindings with <Alt> in them

### ISSUE THREAD

**Issue by nielsdg** [xhorak/firefox-devedition-flatpak#28]
Steps to reproduce:
* Try a keybinding without the \<Alt\> key, such as \<Ctrl\>L to go to the address bar (this works)
* Now try a keybinding *with* \<Alt\>, such as \<Alt\>Left. This fails to work.
This also happens with custom keybindings, such as LastPass' vault-opening \<Ctrl\>\<Alt\>H

**Comment by erAck** [comment]
Outdated, works.
