### ISSUE TITLE
[FirefoxNightlyWayland] Sporadically stops taking keyboard input

### ISSUE THREAD

**Issue by nielsdg** [xhorak/firefox-devedition-flatpak#29]
I'm not able to reliably reproduce this issue, but I've been having this problem where Firefox Nightly (Wayland Build) suddenly no longer allows any keyboard input.

For example, clicking and scrolling works, but nothing happens when I press a keyboard button (neither shortcuts nor anything in input fields or the address bar).

**Comment by erAck** [comment]
I guess this is moot now..
