### ISSUE TITLE
To play audio, you may need to install the required PulseAudio software

### ISSUE THREAD

**Issue by cmurf** [xhorak/firefox-devedition-flatpak#3]
There are several issues in sequence:
a. no audio, e.g. https://www.youtube.com/watch?v=JEsgxHxIr9w
b. when on an example page there's a notification banner under the URL "To play audio, you may need to install the required PulseAudio software." And there's a Lean how button.
c. when clicking the Learn how button, I'm forwarded to https://support.mozilla.org/1/firefox/52.0a2/Linux/en-US/fix-common-audio-and-video-issues but I land on a "Page Not Found" page in Italian (reload and now it's in French, reload again and it's in English)

This is on Fedora 25, the regular Firefox there plays sound OK.

**Comment by xhorak** [comment]
Thanks for the report. It should be fixed now by commit 8970331d39f132f77040760b36659b57c574c35c.

**Comment by jcgruenhage** [comment]
This is broken on Fedora 26 for me again.
