### ISSUE TITLE
[FirefoxNightly] Netflix Video Player Unavailable

### ISSUE THREAD

**Issue by mauricioduarte01** [xhorak/firefox-devedition-flatpak#30]
Hello,
I been trying this Flatpack but for some reason when I try to play any video from Netflix I keep getting this error:

> Whoops, something went wrong...
> Netflix Video Player Unavailable
> 
> We're having trouble playing Netflix on your browser. Please make sure you are on an official version of Firefox.
> Error Code: F7355-1204
> 

With the stable PPA version of Firefox 54.0 I never had any issues, same thing with the Nightly version from the official download https://www.mozilla.org/en-US/firefox/nightly/all/ . Netflix works just great. So it might be a problem related exclusively on the Flatpak version it seems,

I am running Ubuntu 16.04.

Thank you.

EDIT: well I just realize about the existence of this ticket: https://github.com/xhorak/firefox-devedition-flatpak/issues/22

So no solution for now it seems.

**Comment by lblaine** [comment]
Same issue with the Wayland nightly.  Running under Gnome 3 in Antergos linux.

**Comment by xhorak** [comment]
There's been some progress: https://firefox-flatpak.mojefedora.cz/#audio/video-playback Please reopen if that's does not work for you.
