### ISSUE TITLE
[FirefoxNightly] please enable Stylo in the build

### ISSUE THREAD

**Issue by michich** [xhorak/firefox-devedition-flatpak#34]
Hello,
I am using the org.mozilla.FirefoxNightly flatpak, currently 56.0a1 (2017-07-25) (64-bit).
In about:support it shows:

>    Stylo 	false (disabled by build)

Would you please enable Stylo in the build? Adding `ac_add_options --enable-stylo` to the mozconfig might be sufficient.

**Comment by hungrymonkey** [comment]
+1 The only reason why I am using this flatpak is because I can use firefox with new features.

**Comment by xhorak** [comment]
Well I think it is still disabled in official Nightly: see https://bugzilla.mozilla.org/show_bug.cgi?id=1330412 We don't override Nightly build options (well, not completely: https://github.com/xhorak/firefox-devedition-flatpak/blob/master/org.mozilla.FirefoxNightly/firefox-mozconfig but we don't disable the new features).

**Comment by xhorak** [comment]
I guess mozilla has some reason to not enable it by default ATM, so we won't override it.

**Comment by michich** [comment]
The official Nightly has enabled Stylo in the build (though it is runtime-disabled by default and needs toggling in about:config to enable). See this blog post:
https://blog.nightly.mozilla.org/2017/07/25/stylo-is-ready-for-community-testing-on-nightly/
I have downloaded the official Nightly and verified that it is true.

**Comment by xhorak** [comment]
The reason the stylo is not built is that SDK has old llvm compiler and stylo requires more recent. So reopening.

**Comment by xhorak** [comment]
llvm 3.9+ is required, while flatpak freedesktop sdk provides only 3.8: http://flatpak.org/runtimes.html

**Comment by garrett** [comment]
Both the GNOME 3.24 SDK and Freedesktop SDK 1.6 have version 4.0.0 of llvm and clang.

I guess the runtime needs to be updated to either of those (probably the easiest is to just upgrade the Freedesktop SDK Firefox builds against).

**Comment by michich** [comment]
I rechecked today. The org.mozilla.FirefoxNightly flatpak now reports version 57.0a1 (2017-08-04) (64-bit). `flatpak info org.mozilla.FirefoxNightly` shows it's using `Runtime: org.gnome.Platform/x86_64/3.24`. And after enabling layout.css.servo.enabled Stylo now shows as enabled in about:support.
Thanks!
