### ISSUE TITLE
[FirefoxNightly] Printer isn't available and printing to file doesn't work (by default)

### ISSUE THREAD

**Issue by garrett** [xhorak/firefox-devedition-flatpak#35]
This is probably more of a Flatpak issue — the printer dialog has two options:

1. Print to file
2. LPR

My printer doesn't show up.

The dialog looks like this:

![screenshot from 2017-07-26 19-59-31](https://user-images.githubusercontent.com/10246/28636127-ae8740c0-722c-11e7-91c3-3ace38e6ab3a.png)

When I choose Print to file, it defaults to `~/mozilla.pdf`, which doesn't work, as it's sandboxed off. Changing it to `~/Downloads/mozilla.pdf` (or any other filename in that directory) does print a PDF.

Attempting to print to LPR just silently fails. 

Also noteworthy: The printer options don't have color settings, paper selection, collation, etc. (Not surprising, considering all the above.)

---

Portal information: http://flatpak.org/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.Print

**Comment by xhorak** [comment]
Yes, that's something we need to implement.

**Comment by xhorak** [comment]
This should be fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1411589
