### ISSUE TITLE
[FirefoxNightly] [FirefoxNightlyWayland] Firefox Nightly logo was updated — icon also needs updating

### ISSUE THREAD

**Issue by garrett** [xhorak/firefox-devedition-flatpak#38]
As seen in https://twitter.com/FirefoxNightly/status/893577526009880576, Firefox got a new logo!

Here's the largest version (512px) of the new logo I could quickly find in a transparent PNG:

![new logo](https://raw.githubusercontent.com/alrra/browser-logos/f9861f8aad61a4445d990b9c6cef0d80eb53b776/src/firefox-nightly/firefox-nightly_512x512.png)

**Comment by garrett** [comment]
Oops! I built my own version and see it's there. Nevermind; it looks like it works. 😄

**Comment by tidux** [comment]
This is broken again.
