### ISSUE TITLE
Can't resolve /etc/hosts entries

### ISSUE THREAD

**Issue by richard-riverford** [xhorak/firefox-devedition-flatpak#4]
I have an entry in /etc/hosts for a web site I'm running in Docker:

`10.65.23.86 laptop-624`

Firefox Dev Edition installed from the official tarball copes with this fine, but the Flatpak version fails to resolve the hostname.

**Comment by mattaustin** [comment]
I can't resolve machines on my local network (e.g. ``http://mydesktop.local/``)  (usually resolved using avahi - not set in /etc/hosts) - I'm assuming this is probably related.

**Comment by bochecha** [comment]
Since flatpak 0.9.4, the system `/etc/hosts` is now exposed in the sandbox, which means this should work.

Which version of Flatpak were you using?

> I can't resolve machines on my local network (e.g. http://mydesktop.local/) (usually resolved using avahi - not set in /etc/hosts) - I'm assuming this is probably related.

I doubt this is related.
