### ISSUE TITLE
Firefox-nightly-wayland doesnt start in Plasma-wayland session

### ISSUE THREAD

**Issue by mthw0** [xhorak/firefox-devedition-flatpak#48]
Greetings,
So when I try to start ff-nightly-wayland I get:
`(firefox:3): Gdk-WARNING **: Wayland compositor does not support xdg_shell interface, not using Wayland display (firefox:3): GLib-CRITICAL **: g_hash_table_destroy: assertion 'hash_table != NULL' failed
Error: cannot open display: wayland-0
`
Altough it works normally under gnome-wayland. I am running Archlinux with KDE Plasma. Am I missing something?

**Comment by treba123** [comment]
AFAIK that's an issue with xdg_shell in plasma and their xdg_shell v6 support. They'll fix that soon.

**Comment by mthw0** [comment]
FF wayland now starts on Plasma wayland (5.11.95) and 5.12.x (soon) so this issue is solved for now.
