### ISSUE TITLE
Error: Failed to update org.mozilla.FirefoxNightly - Server returned status 404: Not Found

### ISSUE THREAD

**Issue by jgarciao** [xhorak/firefox-devedition-flatpak#52]
``` 
flatpak update

Updating: org.mozilla.FirefoxNightly/x86_64/master from org.mozilla.FirefoxNightly-origin
[-                   ] Downloading metadata: 1/(estimating) 313 bytes
Error: Failed to update org.mozilla.FirefoxNightly/x86_64/master: While pulling app/org.mozilla.FirefoxNightly/x86_64/master from remote org.mozilla.FirefoxNightly-origin: Server returned status 404: Not Found
error: One or more operations failed
```
It seems that the repo is not longer available at https://firefox-flatpak.mojefedora.cz/repo/

**Comment by andrevmatos** [comment]
I'm not having this issue anymore.

**Comment by jgarciao** [comment]
I also don't have the issue now when running flatpak update. 

And now I realized that accessing with the browser to an [actual file inside the repo](https://firefox-flatpak.mojefedora.cz/repo/summary) works well.

Thank you!

**Comment by xhorak** [comment]
Yes, this was due to moving to different hosting.
