### ISSUE TITLE
[FirefoxNightlyWayland] Cursor theme is incorrect

### ISSUE THREAD

**Issue by glaubersm** [xhorak/firefox-devedition-flatpak#53]
Hi
I use a customized cursor theme on my Arch Linux (Gnome 3.26.2) but FirefoxNightlyWayland uses the default cursor theme.

**Comment by anassahmed** [comment]
That's a bug in Flatpak itself, not FirefoxNightlyWayland. It doesn't support host cursor icons.

**Comment by glaubersm** [comment]
are you sure?
Some of flatpaks installed on my system are not affected:
skype
ciano
fragments
peek
babe music player

**Comment by erAck** [comment]
Outdated issue and NightlyWayland was obsoleted.
