### ISSUE TITLE
Built against the old Gnome 3.24 instead of the current 3.26

### ISSUE THREAD

**Issue by dperson** [xhorak/firefox-devedition-flatpak#56]
Would it be possible to build against org.gnome.Platform/x86_64/3.26? Thanks.

**Comment by mthw0** [comment]
@dperson It is questionable whether it would make any difference.

**Comment by dperson** [comment]
Well it will update the versions of GTK and other Gnome libraries that are being updated to better support / fix bugs with Wayland support with each release.

It's not urgent. I was just hoping that it would be a really simple change in the build environment `s/3\.24/3.26/` in a config file type thing. If it breaks the build or is a high LoE please disregard the request. Thanks.

**Comment by treba123** [comment]
This can get closed now, actual build is against 3.26

**Comment by dineshdb** [comment]
what about 3.28 now(of course, if it's not too much to ask)?

**Comment by rugk** [comment]
When updating the runtimes, you also get:
```sh
Info: org.gnome.Platform is end-of-life, with reason: GNOME 3.24 runtime is no longer supported as of 11th January 2019. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform.Locale is end-of-life, with reason: GNOME 3.24 runtime is no longer supported as of 11th January 2019. Please ask your application developer to migrate to a supported platform.
Error: No such metadata object ddb1e6ceddd4831a3db29475155efb00d90a0a7a4acf0ed97621954b5b157f56.commit
Changes complete.
```

**Comment by mustafa1024m** [comment]
I still get the end-of-life warning for 3.24, and I can't remove org.gnome.Platform 3.24 because Firefox depends on it, please change the dependencies so it reflect the real requirement.

**Comment by erAck** [comment]
Outdated, meanwhile building against 3.34
