### ISSUE TITLE
no debug symbols?

### ISSUE THREAD

**Issue by cmurf** [xhorak/firefox-devedition-flatpak#6]
Firefox is crashing on me doing a very specific thing (clicking on "share location" dialog). I found this https://blogs.gnome.org/mclasen/author/mclasen/ about how to get better debug info, but when I do this:
[chris@f25h ~]$ flatpak run --devel --command=sh org.mozilla.FirefoxDevEdition

I get:
Reading symbols from /app/bin/firefox...(no debugging symbols found)...done.

I have org.gnome.Sdk.Debug so I'm guessing the problem is that that there's either no debug for org.mozilla.FirefoxDevEdition.Locale runtime, or no debug for org.mozilla.FirefoxDevEdition app, or both.

**Comment by xhorak** [comment]
Hm, I guess you need to run something like:

`flatpak install org.mozilla.FirefoxDevEdition-origin org.mozilla.FirefoxDevEdition.Debug`

please double check the remote repo if that's `org.mozilla.FirefoxDevEdition-origin` by `flatpak remote-list`

**Comment by xhorak** [comment]
I guess we have debuginfo available, as long as I've tested.
