### ISSUE TITLE
Nightly crashes on about:support on wayland

### ISSUE THREAD

**Issue by treba123** [xhorak/firefox-devedition-flatpak#60]
Hej there, just tried the new nightly with wayland support. Got a fresh profile and installed ublock origin, otherwise a clean install. When trying to access about:support, I get the following error:

```
[Child 104, Chrome_ChildThread] WARNING: pipe error (3): Connection reset by peer: file /run/build/firefox/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
[Child 44, Chrome_ChildThread] WARNING: pipe error (3): Connection reset by peer: file /run/build/firefox/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
```
and firefox crashes

**Comment by sylvestre** [comment]
Could you share the crash id?
you will find it in about:crashes.
thanks

**Comment by treba123** [comment]
Doesn't work there :) gives me "Hmm. That address doesn’t look right." Works in my normal firefox, though. I guess the crash reporter doesn't get build or something?
Also can't find anything in ~/.var/app/org.mozilla.FirefoxNightly

**Comment by xhorak** [comment]
Crashreporter is disabled for our build of Firefox because we don't upload symbols to the crashstat servers.
Thanks for reporting, this is Wayland related, filled as: https://bugzilla.mozilla.org/show_bug.cgi?id=1434266 We're going to track it there.

**Comment by treba123** [comment]
It's now tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1433081

**Comment by treba123** [comment]
Alright, todays build somehow fixed it :)
egl support is still not there, but that's a bigger issue.
