### ISSUE TITLE
Clipboard don't work well in FirefoxNightly using Wayland

### ISSUE THREAD

**Issue by jgarciao** [xhorak/firefox-devedition-flatpak#61]
I've noticed this week that FirefoxNightly behaves strangely recently and after looking at your website I think it may be because of the merged Wayland code

If I copy text in Firefox and paste it in gedit works well. Reverse works too

Instead, if I copy text in a texbox in Firefox (like this issue) and then paste it in Firefox (like next line in this issue) it does nothing. Pasting in other tabs don't work either

I'm using: 
- Debian Stretch
- flatpak 0.10.2.1
- GNOME 3.22.2
- Wayland using nouevau drivers

Using X clipboard works well

**Comment by stransky** [comment]
It's https://bugzilla.mozilla.org/show_bug.cgi?id=1434572

**Comment by jgarciao** [comment]
Thanks for the info!
