### ISSUE TITLE
Firefox Nightly Has No Locale

### ISSUE THREAD

**Issue by Saroufim** [xhorak/firefox-devedition-flatpak#65]
My system is in Spanish but FirefoxNightly is in English. After investigating, I found out that the package never actually downloaded any equivalent locale bundle and there doesn't seem to be any on the repository.

**Comment by erAck** [comment]
We should rather refrain from adding the overhead of generating the Locale pak in builds of **Nightly** (which even might make the build more error prone then because of possibly broken UI locales in master).
