### ISSUE TITLE
Nightly fails to inherit previously existing Nightly profile

### ISSUE THREAD

**Issue by tidux** [xhorak/firefox-devedition-flatpak#67]
The same "me38puq8.default" profile keeps getting recreated and the desired profile ignored even after rsyncing my ~/.mozilla to ~/.var/app/org.mozilla.FirefoxNightly/cache/mozilla.  My profiles.ini confirms that it is meant to be the default profile, and is the only profile in that directory after deleting "me38puq8.default" but before recreating it.  The profile had previously been in use on Nightly via the Arch Linux `firefox-always-nightly` AUR package.

**Comment by tidux** [comment]
I just tested and `flatpak run --filesystem=/home org.mozilla.FirefoxNightly` _does_ pick up the profile I intended to use.  Do I need to do something special to clone a profile?

**Comment by tidux** [comment]
An `rsync -avx` of the old profile's content into the new profile's directory under ~/.var/app did not work either.  Is this flatpak of Firefox just ignoring profile data now?

**Comment by rdstr** [comment]
Remove the slash after `persistent=.mozilla` in the metadata file. Or alternatively you can run the flatpak with `--persist=.mozilla`

**Comment by swick** [comment]
Vanishing profiles is kind of a big deal. The trailing slash has been in firefox flatpak so was it a change in flatpak? Should the slash simply be removed?

**Comment by erAck** [comment]
This trailing slash problem should be fixed with commits c5954e54dcb5cb643ab39b941aa0d54fb8cf3ba8 and cce8c742bf1785fb98eb0fa964adae49b5d63df4
