### ISSUE TITLE
Lacks permissions for few important folders

### ISSUE THREAD

**Issue by tichun** [xhorak/firefox-devedition-flatpak#69]
I often take screenshots and upload them, the default directory for screenshots is the Pictures folder, so only having the permission to access Downloads folder is not enough.
I imagine the same could apply for Music(when downloading music I like to download it directly to that folder), Videos(youtube etc.) and Documents (google docs etc.) folders.

**Comment by dineshdb** [comment]
Is this problem fixed?

**Comment by tichun** [comment]
No, but I think that I've made a duplicate of https://github.com/xhorak/firefox-devedition-flatpak/issues/33
