### ISSUE TITLE
Missing rust compiler during build

### ISSUE THREAD

**Issue by rexcze** [xhorak/firefox-devedition-flatpak#7]
Hello,

when I want to build Firefox I get error about missing rust compiler. 

0:05.87 ERROR: Rust compiler not found.
 0:05.87 To compile rust language sources, you must have 'rustc' in your path.
 0:05.87 See https//www.rust-lang.org/ for more information.
 0:05.87 
 0:05.87 You can install rust by running './mach bootstrap'
 0:05.87 or by directly running the installer from https://rustup.rs/
 0:05.87 
 0:05.89 *** Fix above errors and then restart with\
 0:05.89                "/usr/bin/make -f client.mk build"
 0:05.89 client.mk:379: recipe for target 'configure' failed
 0:05.89 make[1]: *** [configure] Error 1
GNUmakefile:9: recipe for target 'build' failed
make: *** [build] Error 2
Error: module firefox: Proces potomka skončil s kódem 2

$ which rustc
/usr/bin/rustc

Fedora release 25 (Twenty Five)
flatpak-libs-0.8.1-1.fc25.x86_64
flatpak-0.8.1-1.fc25.x86_64
flatpak-builder-0.8.1-1.fc25.x86_64

**Comment by xhorak** [comment]
Thanks for the report. Firefox started to require rust since version 53. Since there's no rust in SDK for this moment, I've used Rustc compiler (14.0) binaries from official site.

**Comment by rexcze** [comment]
Thank you.
