### ISSUE TITLE
Request for stable version and flathub

### ISSUE THREAD

**Issue by tichun** [xhorak/firefox-devedition-flatpak#70]
Mozilla seems to have partnered with Canonical not to use Flatpak as they have released their official Snap, and seem not respond to requests from 'Fedora folks' on their Bugzilla.
It would be awesome to have Firefox available from Flathub, and when Mozilla changes their minds, they could be given ownership.

**Comment by sylvestre** [comment]
We (Mozilla) have been discussing with the "Fedora folks" for quite some time, we are making progress.

**Comment by Saroufim** [comment]
The Flathub folks are adamant not to let anyone publish Firefox on Flathub except Mozilla themselves because apparently there is interest in that (as mentioned in the previous comment by a Mozillan). Thus it is not possible to publish a stable version by a third party like Xhorak.
