### ISSUE TITLE
Asian Fonts Not Rendered on Webpages

### ISSUE THREAD

**Issue by RichieMcG** [xhorak/firefox-devedition-flatpak#71]
This issue is present in both FireFox Dev Edition and FireFox nightly.
 
Previously Chinese, Korean and Japanese fonts were rendered and now they are not. A search was made for fixes but was unsuccessful.

I'm sorry I hadn't updated for a while, so I can't say exactly it broke but the previous version I used wasn't sandboxed and it rendered Asian characters correctly. 

The current edition displays square boxes with hex code inside.

**Comment by henglinli** [comment]
1 install cjk fonts
2 try run below:
 flatpak --command=bash run org.mozilla.FirefoxNightly
fc-cache -f

this problem is font cache not updated with the base system fonts

**Comment by RichieMcG** [comment]
Thanks a lot @henglinli 
I did try refreshing the cache before but I didn't run `flatpak --command=bash run org.mozilla.FirefoxNightly` before running `fc-cache -f`. 

I tried this for the Developers Edition and it worked a treat.
