### ISSUE TITLE
FirefoxNightly won't start if native Firefox 60 is running

### ISSUE THREAD

**Issue by abrodkin** [xhorak/firefox-devedition-flatpak#74]
Noticed quite a strange issue recently - if I have Firefox 60 up and running as a native application (I'm on Fedora 28 64-bit) then on attempt to start FirefoxNightly I'm immediately getting new instance of Firefox 60 instead of Nightly.

Even if I start Nightly from terminal like that:
```
flatpak run org.mozilla.FirefoxNightly
```

If I close native Firefox 60 then nightly could be started perfectly well with either command-line or even .desktop-file (i.e. press "Win" key and find an icon of FFNightly).

**Comment by genodeftest** [comment]
As with every firefox version (and build), you need to run `firefox --new-instance`, preferably even with `firefox --new-instance --ProfileManager`, otherwise firefox will only keep the first instance running.

**Comment by abrodkin** [comment]
OK indeed `flatpak run org.mozilla.FirefoxNightly --new-instance` did work.
So maybe then we want to update Nightly's .desktop file accordingly?

**Comment by genodeftest** [comment]
Or maybe firefox nightly flatpak edition should use a different application ID. That's probably the better solution.

**Comment by abrodkin** [comment]
Maybe so, still that's interesting that I'm pretty sure some time ago (probably before I updated my Fedora from 27 to 28 or it is just native FF bumped to v60) FF Nightly started by .desktop file used to open new instance with Nightly.

**Comment by erAck** [comment]
Meanwhile this is no problem anyore.
