### ISSUE TITLE
Cannot Copy/Paste between X or Wayland windows on Fedora 29 with GNOME 3.29 (XWayland)

### ISSUE THREAD

**Issue by Saroufim** [xhorak/firefox-devedition-flatpak#94]
Copy/pasting between wayland windows and firefox running on Wayland was possible in the past. With Fedora 29, every window can copy/paste to other windows regardless of them being XWayland or regular Wayland windows except this version of Firefox. It cannot neither copy nor paste to or from other windows.

**Comment by wvengen** [comment]
I see this often as well, on Ubuntu 18.04.1. Sometimes it works only on one of the windows (first one? most left one?), sometimes it doesn't work at all.

**Comment by wvengen** [comment]
Diving a bit more into this, I find the following.

- When I copy text from one Firefox window and paste it in another Firefox window, it does not work.
- When I copy text from one Firefox window, paste it into GNOME Terminal, and paste it again in another Firefox window, it works (both in terminal and browser).
- When I copy text from one Firefox window, paste it into another Firefox window, then try to paste it into GNOME Terminal, it doesn't work (both times it doesn't work).
- When I maximize the Firefox window, copy text, paste it into GNOME Terminal, it doesn't work. After unmaximizing and re-copying, and pasting it _usually_ works.

It looks like there is a correlation between paste not working and this error in syslog:
```
org.gnome.Shell.desktop[<pid>]: libinput error: client bug: timer event6 debounce: offset negative (-8ms)
```

Do you see that as well?

**Comment by GorrillaRibs** [comment]
It's been a while since the last update here, but I'm having the issue as well if it's worth anything, on the lastest nightly on wayland. If I un-maximize the window, I can usually copy and paste easier

**Comment by xhorak** [comment]
There's been some fixes to the wayland clipboard recently. Could you please retest now? Currently I'm not able to reproduce this issue. Thank you.

**Comment by wvengen** [comment]
That's great! And indeed, I can paste between X windows and Wayland windows, and the behaviour I [mentioned before](https://github.com/xhorak/firefox-devedition-flatpak/issues/94#issuecomment-419825369) is fixed. Thanks! :fireworks:

**Comment by darioems** [comment]
Uninstalling Clipit Clipboard Manager worked for me.
# dnf remove clipit
And restart session.
